### ISSUE TITLE
Decide on URI format from dewey.info

### ISSUE THREAD

**Issue by nichtich** [scriptotek/mc2skos#11]
*related to #5 and #2 *

In my opinion the default (if no option `--scheme` was given) should be to emit URIs as they were given at dewey.info. To document the choice of URIs I wrote the following paragraph. I am posting it here to discuss whether we can agree on this choice.

---

## DDC URI format

The choice of common URIs is the most important decision because it allows connection of data from multiple sources. The URIs for DDC, as described by Mitchell and Panzer (2013), follow a general pattern with URIs for classes, tables, table numbers, and editions among other parts. URIs for classes and table numbers can further be refined with an edition or date (e.g. http://dewey.info/class/641/2009/, http://dewey.info/class/641/e22/, and http://dewey.info/class/641/e23/2012-08/) and some URIs have an alternative form (e.g. http://dewey.info/class/T2--162/). To minimize the number of possible URIs, only the following URIs should be used:

* DDC as whole: http://dewey.info/scheme/edition/e23/﻿ (particular edition) or http://dewey.info/scheme/ddc/ (general)
* class entry: http://dewey.info/class/551.46/e23/ (particular edition) or 	http://dewey.info/class/551.46/
* DDC table:	http://dewey.info/table/2/e23/ (particular edition) or 	http://dewey.info/table/2/ (general, not found at dewey.info?)
* table entry:	http://dewey.info/class/2--162/e23/ (particular edition) or 	http://dewey.info/class/2--162/  (general)

Note that language editions have no distinct URIs on purpose. The URI format for particular editions of DDC only works until the 23rd edition because this will probably be the last. When OCLC moves from editions to another numbering scheme, this needs to be reflected in an update of this guideline.

---

**Comment by danmichaelo** [comment]
Probably a good idea to use the established pattern by default! I'm incorporating it into the [rewrite](https://github.com/scriptotek/mc2skos/tree/rewrite) branch.

**Comment by danmichaelo** [comment]
Since the rewrite branch was merged quite some time ago, I'm closing this issue. The current default URI pattern is documented on https://github.com/scriptotek/mc2skos#uris . Feel free to re-open the issue if there's more to discuss.
