### ISSUE TITLE
Include examples other than DDC

### ISSUE THREAD

**Issue by nichtich** [scriptotek/mc2skos#13]
MARC 21 Classification format specification [includes examples](https://www.loc.gov/marc/classification/examples.html) of Library of Congress Classification (LCC), National Library of Medicine Classification (NLM) and Universal Decimal Classification (UDC). The latter is an interesting but also complex use case next to DDC. An outline of UDC [has been published as Linked Data](http://udcdata.info/) for comparision. [Next UDC Seminar](http://seminar.udcc.org/) will be 2017, an opportunity to present and discuss. I suppose that UDC in RDF is created [from SQL](http://www.udcc.org/index.php/site/page?view=mrf) but we can ask about availability of its data in MARCXML.

**Comment by nichtich** [comment]
We will provide BK in MARCXML (and SKOS + JSKOS based on mc2skos). Better close this issue after merging 70e346c, I'll better add issue requests for each classification.

**Comment by danmichaelo** [comment]
Thanks for providing BK!
