### ISSUE TITLE
Include tables as concept (sub)schemes

### ISSUE THREAD

**Issue by nichtich** [scriptotek/mc2skos#2]
According to [Mitchell et al (2013)](http://leo.cineca.it/index.php/jlis/article/view/5467) tables have an URI of their own, so in addition to

    <http://dewey.info/class/2--162/> skos:inScheme <http://dewey.info/scheme/>

this should also be stated:

    <http://dewey.info/class/2--162/> skos:inScheme <http://dewey.info/table/2/>

Tables are part of the full scheme but table entries are never topConceptOf the DDC. Unfortunately we cannot check dewey.info how it was originally modelled.

**Comment by danmichaelo** [comment]
Turns out we can: https://web.archive.org/web/20150204021015/http://dewey.info/class/2--4897/about
