### ISSUE TITLE
Add support of MARC authority records format

### ISSUE THREAD

**Issue by nichtich** [scriptotek/mc2skos#29]
[MADS](http://www.loc.gov/standards/mads/) is used for authority files other than classification systems. There are mappings from [MARC 21 Format for Authority Data](https://www.loc.gov/marc/authority/) to MADS and from MADS to RDF (http://www.loc.gov/standards/mads/rdf/) with further mappings from mads-rdf to skos-rdf so the conversion should not be difficult. 

I also found [this tool](https://github.com/kefo/marcauth-2-madsrdf) to convert MADS to SKOS, but it does not seem to be maintained anymore. Having one reliable tool for all MARC formats to SKOS would be better then the current variety of distributed scripts.

Some authority files that provide MARC data for testing (some of them only single records for human inspection): 

* http://id.loc.gov/authorities/ (several)
* https://agclass.nal.usda.gov/download.shtml
* http://scot.curriculum.edu.au/download.asp
* http://realfagstermer.github.io/
* http://natlib.govt.nz/about-us/open-data/nga-upoko-tukutuku-metadata
* http://cantic.bnc.cat/
* http://www.bnc.cat/lenoti/ 
* http://autority.nkp.cz/
* http://www.nlm.nih.gov/mesh/
* https://fr.wikipedia.org/wiki/Rasuqam
* Répertoire de Vedettes-Matière (internal only?)

**Comment by danmichaelo** [comment]
Started working on [feat-aut](https://github.com/scriptotek/mc2skos/tree/feat-aut). Generating relations such as `skos:related` and `skos:broader` is made more difficult by the fact that control numbers references (`$0`) are seldom included{{citation needed}}. Given a complete vocabulary, it's of course possible to do two passes, generating a term-to-identifier map in the first pass, but currently I'm just ignoring `550` fields that do not have `$0`.

**Comment by danmichaelo** [comment]
Merged this in now, feel free to give it a try or add more example files!
