### ISSUE TITLE
Fix release with YAML and vocabularies.yml

### ISSUE THREAD

**Issue by nichtich** [scriptotek/mc2skos#39]
The current release 0.7.1 does not require pyaml and does not include `vocabularies.yml` so it throws an error if installed on a new system (at least this just happened to my colleague).

**Comment by danmichaelo** [comment]
Hm, that's strange. It should have been included in that release:

https://github.com/scriptotek/mc2skos/blob/v0.7.1/setup.py

But I can reproduce the problem on Python 2.7:

```
pyenv shell 2.7.13
virtualenv ENV --no-site-packages
```

Seems like both `pyaml` and `future` are not included as requirements in the py2.7.egg.

**Comment by danmichaelo** [comment]
Ah, perhaps I should move some stuff from `setup_requires` to `install_requires`. I've never been very good at packaging python packages..

**Comment by danmichaelo** [comment]
Still a bit of a mystery to me why `rdflib-jsonld` [https://travis-ci.org/scriptotek/mc2skos/jobs/290045741 fails] when `rdflib` isn't included in `setup_requires`, but at least the current setup in 0.7.2 seems to work fine.
