### ISSUE TITLE
Language tags

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/mc2skos#4]
Atm. we have `@nb` hardcoded. We could perhaps use the value from `040 $b`, and default to English.

I'm a bit puzzled by the definition for `040 $b` in Marc21 Classification though: “MARC code for the language used in the textual portions of the record in the Note fields (6XX).” (https://www.loc.gov/marc/classification/cd040.html). Wonder why they chose to limit it to note fields.. In Marc21 Bibliographic the definition is more general. 

For converting from ISO 639-2 to 639-1 I've used [iso-639](https://pypi.python.org/pypi/iso-639) before.

**Comment by nichtich** [comment]
Yes, `040 $b` is the right place. I've looked up in German DDC, it's in there with `ger`.
