### ISSUE TITLE
Support import and/or export of MADS?

### ISSUE THREAD

**Issue by nichtich** [scriptotek/mc2skos#46]
For [MADS](https://www.loc.gov/standards/mads/) there is a MARC-XML Authorities to MADS XML Stylesheet and a [MADS RDF ontology](https://www.loc.gov/standards/mads/rdf/). The question is whether and where MADS is actually relevant compared to SKOS. Anyway MADS should at least be mentioned.

**Comment by danmichaelo** [comment]
Not sure. Haven't looked, but I would expect there's already tools for converting MARC-XML <-> MADS. Think I've read that the formats are roundtrip compatible, but could be wrong.

**Comment by nichtich** [comment]
Ok, MADS export is already covered by existing stylesheets. We have a use case for creating MARC authority records from JSKOS but this does not involve MADS.
