### ISSUE TITLE
New release with CHANGES.md

### ISSUE THREAD

**Issue by nichtich** [scriptotek/mc2skos#49]
@danmichaelo could you release a new version including the just merged addition of rvk, please? I'd also include a `CHANGES.md`, just copy this:

~~~markdown
## 0.10.2 (2018-0...

* Natively support processing of RVK

## 0.10.1 (2018-04-12)

## 0.10.0 (2018-04-05)

## 0.9.0 (2018-01-28)

## 0.8.0 (2017-12-04)

## 0.7.3 (2017-10-29)

## 0.7.2 (2017-10-16)

## 0.7.1 (2017-07-26)

## 0.7.0 (2017-07-22)

## 0.6.0 (2017-06-28)

## 0.5.1 (2017-02-10)

## 0.5.0 (2017-02-09)

## 0.4.0 (2017-01-17)

## 0.3.1 (2017-08-15)

* First release as package
~~~

**Comment by danmichaelo** [comment]
Done! As for release notes, they're already https://github.com/scriptotek/mc2skos/releases and I would prefer not having to maintain it in two places. Perhaps a CHANGES.md file that refers to https://github.com/scriptotek/mc2skos/releases would do?
