### ISSUE TITLE
Extract mappings from field 024

### ISSUE THREAD

**Issue by nichtich** [scriptotek/mc2skos#55]
MARC Authority Field [024](http://www.loc.gov/marc/authority/ad024.html) can contain corresponding identifier in other systems, this should become `skos:exactMatch`. Examples can be found in GND (see #56), see <http://coli-conc.gbv.de/concordances/gnd/>

**Comment by danmichaelo** [comment]
Added a few vocabularies (after doing some refactoring): https://github.com/scriptotek/mc2skos/commit/03470a3f18d3f3a4ec0b13b2137f1fdebf3941d4#diff-69bc818a87939d320f5974936d9d818d

**Comment by danmichaelo** [comment]
Closing this, but feel free to add more vocabularies to vocabularies.yml!
