### ISSUE TITLE
Support converting GND authority file record

### ISSUE THREAD

**Issue by nichtich** [scriptotek/mc2skos#56]
GND records provided by the German National Library (e.g. http://d-nb.info/1020118989/about/marcxml) cannot be converted because:

* Field 008[11] is set to `n` (Not applicable) instead of `z` (Other)
* `gnd` is not specified in 040$f

The first may be fixed in mc2skos by also allowing `n` but the second needs to be done by German National Library. 

After both changes (an example is included in https://github.com/gbv/mc2skos/blob/gnd/examples/gnd-1020118989.xml), the converted RDF contains an empty  string triple:

    skos:note ""@de ;

This should better be fixed in mc2skos.

Finally GND records contain mappings via field 024 to be converted too (#55).

**Comment by danmichaelo** [comment]
Do you understand why they use "n"? Seems a bit strange to me, but I'm not totally sure I understand the semantics of it :)

Are you in contact with DNB about adding 040$f? That would be good to have indeed.

**Comment by nichtich** [comment]
I got feedback, they are not going to change the date. Can we just accept `n` in `008[11]` instead of rejecting the records? The connection to GND still needs to be given explicitly via `--scheme` and `--uri`:

     mc2skos --scheme http://d-nb.info/gnd/ --uri 'http://d-nb.info/gnd/{control_number}' examples/gnd-4003412-4.xml

I'd like to simplifiy this, e.g.

    mc2skos --scheme gnd

To set a default value of 040$4 or 084$a.

**Comment by danmichaelo** [comment]
You didn't get an explanation as for why they prefer "n"?

The short form makes good sense, so I added support for that.
