### ISSUE TITLE
Support URIs in fld 856

### ISSUE THREAD

**Issue by CaptSolo** [scriptotek/mc2skos#67]
Currently, mc2skos does not export URIs that appear in field 856.
```
  <datafield tag="856" ind1="4" ind2="0">
    <subfield code="u">http://viaf.org/viaf/113418055</subfield>
    <subfield code="y">VIAF ID</subfield>
  </datafield>
```

Would it be possible to add support for exporting these URIs (when ind2 is 0, indicating that this is the same resource elsewhere)?

I could try adding it myself if someone could tell me what files / functions / ... need to be modified.

**Comment by danmichaelo** [comment]
(Sorry for the slow response) Interesting, I haven't really seen 8XX fields in authority records before. Do you use 856 to create mappings between your own records and VIAF? Something like `skos:exactMatch`? 

mc2skos currently supports mapping relations from 7XX fields, see https://github.com/scriptotek/mc2skos#mapping-schema-for-marc21-authority

**Comment by CaptSolo** [comment]
I checked with colleagues: we used to use fld 856 for linking to the same entity on VIAF (hence it can appear in some records) but we are not doing that any more (fields 7XX are used instead).

I will close this issue.

**Comment by danmichaelo** [comment]
Thanks!
